### ISSUE TITLE
Version 0.8.5 raise error

### ISSUE THREAD

**Issue by legendado** [djezzzl/database_consistency#64] opened 2020-09-22 06:24 UTC
Hello, after bump version to `0.8.5` I've an error:
```ruby
<===begin===>
[1mTraceback[m (most recent call last):
	24: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	23: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	22: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `<main>'
	21: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `load'
	20: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/bin/database_consistency:44:in `<top (required)>'
	19: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency.rb:46:in `run'
	18: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:30:in `report_if_enabled?'
	 3: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:23:in `report'
	 2: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:32:in `check'
	 1: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:92:in `converted_type'
/home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `type': [1mundefined method `sql_type' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
<===end===>
<===begin===>
[1mTraceback[m (most recent call last):
	24: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	23: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	22: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `<main>'
	21: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `load'
	20: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/bin/database_consistency:44:in `<top (required)>'
	19: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency.rb:46:in `run'
	18: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:30:in `report_if_enabled?'
	 3: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:23:in `report'
	 2: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:32:in `check'
	 1: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:92:in `converted_type'
/home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `type': [1mundefined method `sql_type' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
<===end===>
<===begin===>
[1mTraceback[m (most recent call last):
	24: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	23: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	22: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `<main>'
	21: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `load'
	20: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/bin/database_consistency:44:in `<top (required)>'
	19: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency.rb:46:in `run'
	18: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:30:in `report_if_enabled?'
	 3: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:23:in `report'
	 2: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:32:in `check'
	 1: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:92:in `converted_type'
/home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `type': [1mundefined method `sql_type' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
<===end===>
<===begin===>
[1mTraceback[m (most recent call last):
	24: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	23: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	22: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `<main>'
	21: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `load'
	20: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/bin/database_consistency:44:in `<top (required)>'
	19: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency.rb:46:in `run'
	18: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:30:in `report_if_enabled?'
	 3: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:23:in `report'
	 2: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:32:in `check'
	 1: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:92:in `converted_type'
/home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `type': [1mundefined method `sql_type' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
<===end===>
<===begin===>
[1mTraceback[m (most recent call last):
	24: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	23: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	22: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `<main>'
	21: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `load'
	20: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/bin/database_consistency:44:in `<top (required)>'
	19: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency.rb:46:in `run'
	18: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:30:in `report_if_enabled?'
	 3: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:23:in `report'
	 2: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:32:in `check'
	 1: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:92:in `converted_type'
/home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `type': [1mundefined method `sql_type' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
<===end===>
<===begin===>
[1mTraceback[m (most recent call last):
	24: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	23: from /home/dell/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	22: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `<main>'
	21: from /home/dell/.rvm/gems/ruby-2.6.5/bin/database_consistency:23:in `load'
	20: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/bin/database_consistency:44:in `<top (required)>'
	19: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency.rb:46:in `run'
	18: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:30:in `report_if_enabled?'
	 3: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/base_checker.rb:23:in `report'
	 2: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:32:in `check'
	 1: from /home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:92:in `converted_type'
/home/dell/.rvm/gems/ruby-2.6.5/gems/database_consistency-0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `type': [1mundefined method `sql_type' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
<===end===>
```

**Comment by djezzzl** [comment] 2020-09-22 06:28
Hi, thank you letting me know! 

Could you please share your database version and active record version?

**Comment by legendado** [comment] 2020-09-22 06:31
Sure
database: `postgres 12`
activerecord: `6.0.3.3`

**Comment by tdeo** [comment] 2020-09-22 06:48
Hi, running into the same problem here, 
I could track it down first when using custom association keys as symbols, and on this line :
https://github.com/djezzzl/database_consistency/blob/v0.8.5/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb#L78

`column.name` is a string but column_name is a symbol, so `find` returns nil

After changing it to `find { |column| column.name == column_name.to_s }`, it fixes this problem.

I'm still having the same bug however when using `through` associations, for instance with active storage when declaring `has_one_attached :avatar`, it defines a has_one through association named `avatar_blob`

**Comment by djezzzl** [comment] 2020-09-22 07:11
Thank you, so I'll fix today a finder and remove "through" associations from supporting

**Comment by djezzzl** [comment] 2020-09-22 08:38
Hey guys, I've provided a fix for both problems (at least AFAIU) https://github.com/djezzzl/database_consistency/pull/65. It's already merged and released as `0.8.6`. Please try it out and let me know if that helps. 

BTW, I couldn't reproduce both issues locally, could you please give me a little bit more context so I can write a regression test?

**Comment by djezzzl** [comment] 2020-09-22 08:38
Feel free to reopen the issue if needed 👍

**Closed by djezzzl** 2020-09-22 08:38 UTC

**Comment by tdeo** [comment] 2020-09-22 10:24
I imagine a test for has_many_through would look like this (don't have the DB setup locally so can't run it though)
```
  context 'with has_many through: association' do
    let(:users_company_class) { define_class('UsersCompany', :users_companies) { |klass| klass.belongs_to :user; klass.belongs_to :company }}
    let(:company_class) { define_class('Company', :companies) { |klass| klass.has_many :users, through: :users_companies } }
    let(:base_type) { :bigint }

    before do
      base = base_type

      define_database do
        create_table :users, id: base
        create_table :companies, id: base

        create_table :users_companies do |t|
          t.send(base, :company_id)
          t.send(base, :user_id)
        end
      end
    end
```

and with custom symbol foreign_key :
```
  context 'with has_many through: association' do
    let(:user_class) { define_class('User', :users) { |klass| klass.has_many :companies, foreign_key: :owner_id }}
    let(:company_class) { define_class('Company', :companies) }
    let(:base_type) { :bigint }

    before do
      base = base_type

      define_database do
        create_table :users, id: base 
        create_table :companies, id: base do |t|
          t.send(base, :owner_id)
        end
      end
    end
```
```
